%opt = true: png da tabela; opt = false: latex da tabela
%y: array de resultados dos ensaios experimentais
%ymodel: valores previstos pelo modelo
%p: grau do modelo
%nfat: numero de fatores do modelo

function anovatab(y, ymodel, opt, p, nfat)
    %caracteristicas dos ensaios
    avg_y = mean(y);
    n = length(y);

    %calculo dos residuos
    residuals = y - ymodel;

    %somas quadraticas
    ss_total = sum((y - avg_y).^2);
    ss_residual = sum(residuals.^2);
    ss_reg = ss_total - ss_residual;

    %graus de liberdade
    gl_total = n - 1;
    gl_reg = nchoosek(nfat + p, p) - 1;
    gl_residual = gl_total - gl_reg;

    %medias quadraticas
    sm_total = ss_total / gl_total;
    sm_residual = ss_residual / gl_residual;
    sm_reg = ss_reg / gl_reg;

    %coeficiente de determinação
    r_squared = 1 - (ss_residual / ss_total);
    
    if opt
        dados = {
            'Regressão', sprintf('%.2f', ss_reg), gl_reg, sprintf('%.2f', sm_reg);
            'Resíduos',  sprintf('%.2f', ss_residual), gl_residual, sprintf('%.2f', sm_residual);
            'Total',     sprintf('%.2f', ss_total), gl_total, sprintf('%.2f', sm_total);
            '% de variação explicada', sprintf('%.2f%%', r_squared * 100), '', ''
            };

        colname = {
            'Fonte de variação'
            'Soma quadrática'
            'Nº de g.l.'
            'Média quadrática'
            };

        t = table(dados(:,1), dados(:,2), dados(:,3), dados(:,4), ...
            'VariableNames', {'Fonte_de_variacao', 'Soma_quadratica', 'GL', 'Media_quadratica'}, ...
            'VariableNames', colname);

        disp(t);
    else
        fpw = fopen("anovatab.txt", "w");

        if ~fpw
            disp("Erro ao abrir o arquivo de escrita da tabela");
        end

        %codigo latex da tabela
        %são necessários os pacotes tabularx, float, array e booktabs
        tabtex = sprintf([ ...
            '\\begin{table}[H]\n' ...
            '\t\\centering\n\n' ...
            '\t\\caption{Análise de variância para o ajuste de um modelo do $%d^{\\circ}$ grau aos dados da Tabela~\\ref{<<inserir referencia>>}.}\n' ...
            '\t\\label{tab:anovatab}\n\n' ...
            '\t\\renewcommand{\\arraystretch}{1.5}\n\n' ...
            '\t\\begin{tabular}{\n' ...
            '\t>{\\centering\\arraybackslash}m{0.2\\linewidth}\n' ...
            '\t>{\\centering\\arraybackslash}m{0.2\\linewidth}\n' ...
            '\t>{\\centering\\arraybackslash}m{0.2\\linewidth}\n' ...
            '\t>{\\centering\\arraybackslash}m{0.2\\linewidth}\n' ...
            '\t}\n\n' ...
            '\t\\toprule\n' ...
            '\t\\textbf{Fonte de variação} & \\textbf{Soma quadrática} & \\textbf{Nº de g.l.} & \\textbf{Média quadrática} \\\\ \n' ...
            '\t\\midrule\n' ...
            '\tRegressão & %.2f & %d & %.2f \\\\ \n' ...
            '\tResíduos & %.2f & %d & %.2f \\\\ \n' ...
            '\t\\midrule\n' ...
            '\tTotal & %.2f & %d & %.2f \\\\ \n' ...
            '\t\\midrule\n' ... 
            '\t\\%% de variação explicada & %.2f\\%% & & \\\\ \n' ...
            '\t\\bottomrule\n' ...
            '\t\\end{tabular}\n' ...
            '\\end{table}\n' ...
            ], p, ss_reg, gl_reg, sm_reg, ...             
            ss_residual, gl_residual, sm_residual, ... 
            ss_total, gl_total, sm_total, ...          
            r_squared * 100);

        fprintf(fpw, "%s\n", tabtex);
        fclose(fpw);
    end
end